"use client";

import { useAllInsights } from "@/lib/hooks/useInsights";
import { generateInsight } from "@/lib/api";
import { Brain, Sparkles } from "lucide-react";
import { formatDistanceToNow } from "date-fns";
import { useState } from "react";

export default function InsightsPage() {
  const { data, isLoading, mutate } = useAllInsights();
  const [generating, setGenerating] = useState(false);
  const insights = data?.data ?? [];

  const handleGenerate = async () => {
    setGenerating(true);
    try {
      await generateInsight();
      await mutate();
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="font-heading text-xl font-bold">AI Insights History</h1>
        <button
          onClick={handleGenerate}
          disabled={generating}
          className="flex items-center gap-1.5 px-4 py-2 bg-accent-cyan/10 text-accent-cyan rounded-lg text-sm hover:bg-accent-cyan/20 transition-colors disabled:opacity-50"
        >
          <Sparkles className="w-4 h-4" />
          {generating ? "Generating..." : "Generate New Insight"}
        </button>
      </div>

      {isLoading ? (
        <div className="space-y-4">
          {[...Array(3)].map((_, i) => (
            <div
              key={i}
              className="h-32 bg-bg-card border border-border rounded-lg animate-pulse"
            />
          ))}
        </div>
      ) : insights.length === 0 ? (
        <div className="text-center py-20">
          <Brain className="w-12 h-12 text-text-muted mx-auto mb-4" />
          <p className="text-text-muted">
            No insights generated yet. Click &quot;Generate New Insight&quot; or wait for
            the daily 08:00 UTC generation.
          </p>
        </div>
      ) : (
        <div className="space-y-4">
          {insights.map((insight: any) => {
            let parsed: any = null;
            try {
              parsed = JSON.parse(insight.content);
            } catch {}

            return (
              <div
                key={insight.id}
                className="bg-bg-card border border-border rounded-lg p-6"
              >
                <div className="flex items-start justify-between mb-3">
                  <h3 className="font-heading text-lg font-semibold text-accent-cyan">
                    {parsed?.title || insight.title || "AI Trend Briefing"}
                  </h3>
                  {insight.generated_at && (
                    <span className="text-xs text-text-muted">
                      {formatDistanceToNow(new Date(insight.generated_at), {
                        addSuffix: true,
                      })}
                    </span>
                  )}
                </div>

                {parsed?.executive_summary && (
                  <p className="text-sm text-text-primary leading-relaxed mb-4">
                    {parsed.executive_summary}
                  </p>
                )}

                {parsed?.key_trends && (
                  <div className="grid grid-cols-2 gap-2 mb-4">
                    {parsed.key_trends.map((kt: any, i: number) => (
                      <div
                        key={i}
                        className="p-2 bg-bg-secondary rounded border border-border/50"
                      >
                        <span className="text-xs font-semibold text-accent-amber">
                          {kt.trend}
                        </span>
                        <p className="text-[11px] text-text-muted mt-0.5">
                          {kt.why_it_matters}
                        </p>
                      </div>
                    ))}
                  </div>
                )}

                {insight.top_trends && (
                  <div className="flex flex-wrap gap-1.5">
                    {insight.top_trends.map((t: string, i: number) => (
                      <span
                        key={i}
                        className="text-[10px] bg-accent-cyan/10 text-accent-cyan px-2 py-0.5 rounded"
                      >
                        {t}
                      </span>
                    ))}
                  </div>
                )}

                <div className="mt-3 pt-3 border-t border-border/50 text-[10px] text-text-muted">
                  Generated by {insight.model_used} via Ollama
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
